[build]
    command = "hugo --gc --minify"
    publish = "public"

[context.production.environment]
    HUGO_ENV           = "production"
    HUGO_VERSION       = "0.124.1"
    GO_VERSION         = "1.22.3"

[context.split1]

    [context.split1.environment]
    HUGO_ENV     = "production"
    HUGO_VERSION = "0.124.1"
    GO_VERSION   = "1.22.3"

[context.deploy-preview]

    [context.deploy-preview.environment]
    HUGO_VERSION = "0.124.1"
    GO_VERSION   = "1.22.3"

[context.branch-deploy]

    [context.branch-deploy.environment]
    HUGO_VERSION = "0.124.1"
    GO_VERSION   = "1.22.3"
